[[records]]
name = 'localhost' # Domain
type = 'A' # Record type (only A available)
value = '127.0.0.1' # Address
ttl = 300 # Cache time

[[records]]
name = 'my.google'
type = 'A'
value = '142.251.16.138'
ttl = 0
